<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>FlurNetz.Api</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>flurnetz-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlurNetz.Modules.Identity.Contracts\FlurNetz.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="..\FlurNetz.Modules.Identity\FlurNetz.Modules.Identity.csproj" />
    <ProjectReference Include="..\FlurNetz.Modules.Shop.Contracts\FlurNetz.Modules.Shop.Contracts.csproj" />
    <ProjectReference Include="..\FlurNetz.Modules.Shop\FlurNetz.Modules.Shop.csproj" />
    <ProjectReference Include="..\FlurNetz.Persistence\FlurNetz.Persistence.csproj" />
  </ItemGroup>

</Project>
